-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 9ce45609a92f648c87b42207410386fd69a5d1e5
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: ^test_data/
    -   id: autopep8-wrapper
        exclude: ^test_data/
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
        exclude: ^test_data/
-   repo: git@github.com:pre-commit/pre-commit
    sha: 4352d45451296934bc17494073b82bcacca3205c
    hooks:
    -   id: validate_config
    -   id: validate_manifest
-   repo: git@github.com:asottile/reorder_python_imports
    sha: 04ab8446d0c82026e7d7b0c1ba96bab1cca8185e
    hooks:
    -   id: reorder-python-imports
        exclude: ^test_data/
